# Generated by Django 4.2.6 on 2023-10-29 18:41

from django.db import migrations, models
import django.db.models.deletion
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceInflacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY/MM', max_length=6)),
                ('indice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SaludFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_cedula', models.CharField(max_length=11, unique=True, validators=[posts.validators.validate_cedula])),
                ('nombre_cliente', models.CharField(default='Nombre Predeterminado', max_length=100)),
                ('indicador', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('comentario', models.TextField()),
                ('monto_total_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_moneda', models.CharField(max_length=3)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCrediticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc_empresa_adeuda', models.CharField(max_length=15)),
                ('concepto_deuda', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cliente_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_crediticio', to='posts.saludfinanciera', to_field='cliente_cedula')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaServicioTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tasacambiaria')),
            ],
        ),
    ]
