# Generated by Django 4.2.6 on 2023-10-30 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_historialcrediticio_visitas_indiceinflacion_visitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcrediticio',
            name='visitas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='historial_crediticio', to='posts.visitasmodel'),
        ),
    ]
