# Generated by Django 4.2.6 on 2023-10-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_indiceinflacion_visitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcrediticio',
            name='visitas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historial_crediticio', to='posts.visitasmodel'),
        ),
        migrations.AlterField(
            model_name='indiceinflacion',
            name='visitas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='indice_inflacion', to='posts.visitasmodel'),
        ),
        migrations.AlterField(
            model_name='saludfinanciera',
            name='visitas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salud_financiera', to='posts.visitasmodel'),
        ),
        migrations.AlterField(
            model_name='tasacambiaria',
            name='visitas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasa_cambiaria', to='posts.visitasmodel'),
        ),
    ]
